package com.example.ledger.mapper;

import com.example.ledger.pojo.WareHourse;
import com.example.ledger.pojo.WareHourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WareHourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    long countByExample(WareHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int deleteByExample(WareHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int insert(WareHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int insertSelective(WareHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    List<WareHourse> selectByExample(WareHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    WareHourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int updateByExampleSelective(@Param("record") WareHourse record, @Param("example") WareHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int updateByExample(@Param("record") WareHourse record, @Param("example") WareHourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int updateByPrimaryKeySelective(WareHourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    int updateByPrimaryKey(WareHourse record);
}