package com.example.ledger.pojo;

import java.util.Date;

public class WareHourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.goodsId
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.number
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.Warehousing
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    private Date warehousing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.goodsName
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    private String goodsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.goodsId
     *
     * @return the value of warehouse.goodsId
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.goodsId
     *
     * @param goodsid the value for warehouse.goodsId
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.number
     *
     * @return the value of warehouse.number
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.number
     *
     * @param number the value for warehouse.number
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.Warehousing
     *
     * @return the value of warehouse.Warehousing
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public Date getWarehousing() {
        return warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.Warehousing
     *
     * @param warehousing the value for warehouse.Warehousing
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public void setWarehousing(Date warehousing) {
        this.warehousing = warehousing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.goodsName
     *
     * @return the value of warehouse.goodsName
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.goodsName
     *
     * @param goodsname the value for warehouse.goodsName
     *
     * @mbg.generated Tue Jun 27 21:12:56 CST 2023
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }
}